DROP TABLE MANTENIMIENTO;
DROP TABLE PROVEEDOR;
DROP TABLE MAQUINARIA;

CREATE TABLE MAQUINARIA (
    ID              SMALLSERIAL PRIMARY KEY,
    NUMERO          SMALLINT,
    DESCRIPCION     VARCHAR,
    MARCA           VARCHAR,
    MODELO          VARCHAR,
    NSERIE          VARCHAR,
    PERIODO         VARCHAR,
    ACTIVO_FIJO     VARCHAR,
    ZONA            VARCHAR,
    PLANTA          VARCHAR(1),
    FECHA_COMPRA    DATE,
    EN_USO          BOOLEAN     DEFAULT TRUE,
    EN_SERVICIO     BOOLEAN     DEFAULT TRUE,
    GIMNASIOLUISON  BOOLEAN     DEFAULT TRUE,
    CAUSA           VARCHAR
); -- NOTE Include gym options (boolean)

CREATE TABLE PROVEEDOR (
    ID              SMALLSERIAL PRIMARY KEY,
    NOMBRE          VARCHAR,
    COMPANIA        VARCHAR
);

CREATE TABLE MANTENIMIENTO (
    ID              SMALLSERIAL PRIMARY KEY,
    MAQUINA         INT         REFERENCES MAQUINARIA(ID),
    PROVEEDOR       INT         REFERENCES PROVEEDOR(ID),
    FECHA           DATE        DEFAULT CURRENT_DATE,
    DESCRIPCION     VARCHAR,
    EMERGENCIA      BOOLEAN     DEFAULT FALSE,
    REFACCIONES     BOOLEAN     DEFAULT FALSE,
    REEMPLAZO       BOOLEAN     DEFAULT FALSE,
    GARANTIA        BOOLEAN     DEFAULT FALSE,
    COSTO           FLOAT,
    NUMEROORDEN     VARCHAR
);
