DROP TABLE MANTENIMIENTO;
DROP TABLE PROVEEDOR;
DROP TABLE MAQUINARIA;

CREATE TABLE MAQUINARIA (
    ID              SMALLSERIAL PRIMARY KEY,
    NUMERO          SMALLINT,
    DESCRIPCION     VARCHAR,
    MARCA           VARCHAR     NOT NULL,
    MODELO          VARCHAR,
    NSERIE          VARCHAR,
    PERIODO         VARCHAR,
    ACTIVO_FIJO     VARCHAR,
    ZONA            VARCHAR,
    PLANTA          VARCHAR(1),
    FECHA_COMPRA    DATE,
    EN_USO          BOOLEAN     DEFAULT TRUE,
    EN_SERVICIO     BOOLEAN     DEFAULT TRUE,
    CAUSA           VARCHAR
);

CREATE TABLE PROVEEDOR (
    ID              SMALLSERIAL PRIMARY KEY,
    NOMBRE          VARCHAR,
    COMPANIA        VARCHAR
);

CREATE TABLE MANTENIMIENTO (
    ID              SMALLSERIAL PRIMARY KEY,
    MAQUINA         INT         REFERENCES MAQUINARIA(ID),
    PROVEEDOR       INT         REFERENCES PROVEEDOR(ID), -- FOREIGN KEY TO PROVEEDORES
    FECHA           DATE,
    DESCRIPCION     VARCHAR,
    EMERGENCIA      BOOLEAN,
    REFACCIONES     BOOLEAN,
    REEMPLAZO       BOOLEAN,
    GARANTIA        BOOLEAN,
    COSTO           FLOAT,
    NUMEROORDEN     VARCHAR
);





-- ! PRUEBA PARA PROVEEDORES, REMOVER CUANDO NO SE UTILICE COMO TEST
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('ANDRES', 'UDLAP');
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('CHARLY', 'TSYSTEMS');
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('ERICK', 'EMPRESA');
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('JACK', 'OVERWATCH');


-- ! PRUEBA PARA MANTENIMIENTOS, REMOVER CUANDO NO SE UTILICE COMO PRUEBA
INSERT INTO MANTENIMIENTO(MAQUINA, PROVEEDOR, FECHA, DESCRIPCION, EMERGENCIA, REFACCIONES, REEMPLAZO, GARANTIA, COSTO, NUMEROORDEN) VALUES (1, 1, CURRENT_DATE, 'CAMBIO DE RUEDAS', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 5200.3, 12);
INSERT INTO MANTENIMIENTO(MAQUINA, PROVEEDOR, FECHA, DESCRIPCION, EMERGENCIA, REFACCIONES, REEMPLAZO, GARANTIA, COSTO, NUMEROORDEN) VALUES (15, 2, CURRENT_DATE, 'DEFECTO', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 734, 14);