DROP TABLE MAQUINARIA;

CREATE TABLE MAQUINARIA (
    NUMERO          SMALLINT,
    DESCRIPCION     VARCHAR,
    MARCA           VARCHAR NOT NULL,
    MODELO          VARCHAR(20),
    NSERIE          VARCHAR(25) PRIMARY KEY,
    PERIODO         VARCHAR(8),
    ACTIVOFIJO      VARCHAR(12),
    ZONA            VARCHAR(30),
    PLANTA          VARCHAR(1),
    FECHA_COMPRA    DATE,
    EN_USO          BOOLEAN,
    EN_SERVICIO     BOOLEAN,
    CAUSA           VARCHAR(100)
);


-- * REGISTROS

-- * ZONA DE CAMINADORAS
'N°','DESCRIPCIÓN','MARCA','MODELO','N° SERIE','PERIODO','ACTIVO FIJO'
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL148800', 'OT 2013', 'AF/014264', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150480', 'OT 2013', 'AF/014270', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL149874', 'OT 2013', 'AF/014266', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL151435', 'OT 2013', 'AF/014271', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (5, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150479', 'OT 2013', 'AF/014269', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (6, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL148799', 'OT 2013', 'AF/014265', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (7, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150489', 'OT 2013', 'AF/014268', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (8, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150488', 'OT 2013', 'AF/014267', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (9, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL179135', 'OT 2013', 'AF/019988', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (10, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121874', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (11, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121896', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (12, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121897', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (13, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121560', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (14, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121898', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (15, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121558', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (16, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121893', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (17, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121895', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (18, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121894', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (19, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121883', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (20, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121875', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (21, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121876', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (22, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121888', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (23, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121882', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (24, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121886', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (25, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121879', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (26, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121899', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (27, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121878', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (28, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121901', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (29, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121877', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (30, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121881', 'VR 2019', 'CAMINADORAS', 'A', 'true', 'true');

-- * ZONA DE ELIPTICAS
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX120509', 'VR 2016', 'AF/014272', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX118997', 'VR 2016', 'AF/014275', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX119240', 'VR 2016', 'AF/014276', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX127477', 'VR 2016', 'AF/014281', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (5, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX121349', 'VR 2016', 'AF/014279', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (6, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX119242', 'VR 2016', 'AF/014278', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (7, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX120335', 'VR 2016', 'AF/014274', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (8, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX118998', 'VR 2016', 'AF/014277', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (9, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX121350', 'VR 2016', 'AF/014280', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (10, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' ,'CXX120336', 'VR 2016', 'AF/014273', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (11, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110921', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (12, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110595', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (13, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110590', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (14, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110589', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (15, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110594', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (16, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110591', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (17, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110592', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (18, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110596', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (19, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110593', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (20, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110920', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (21, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX','CXX143851', 'VR 2016', 'AF/019989', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (22, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX','CXX143845', 'VR 2016', 'AF/019990', 'ELIPTICAS', 'A', 'true', 'true');

-- * ZONA DE BICICLETAS
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25776, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25767, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25856, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25721, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (5, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25785, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (6, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25782, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (7, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25727, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (8, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25762, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (9, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25764, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (10, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25752, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (11, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25757, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (12, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25758, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (13, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25741, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (14, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25761, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (15, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25737, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');

-- * ZONA DE ESCALADORAS
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106281', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'BICItrue');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106273', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106291', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA (NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVOFIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106288', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');
