DROP TABLE MANTENIMIENTO;
DROP TABLE PROVEEDOR;
DROP TABLE MAQUINARIA;

CREATE TABLE MAQUINARIA (
    ID              SMALLSERIAL PRIMARY KEY,
    NUMERO          SMALLINT,
    DESCRIPCION     VARCHAR,
    MARCA           VARCHAR,
    MODELO          VARCHAR,
    NSERIE          VARCHAR,
    PERIODO         VARCHAR,
    ACTIVO_FIJO     VARCHAR,
    ZONA            VARCHAR,
    PLANTA          VARCHAR(1),
    FECHA_COMPRA    DATE,
    EN_USO          BOOLEAN     DEFAULT TRUE,
    EN_SERVICIO     BOOLEAN     DEFAULT TRUE,
    CAUSA           VARCHAR
);

CREATE TABLE PROVEEDOR (
    ID              SMALLSERIAL PRIMARY KEY,
    NOMBRE          VARCHAR,
    COMPANIA        VARCHAR
);

CREATE TABLE MANTENIMIENTO (
    ID              SMALLSERIAL PRIMARY KEY,
    MAQUINA         INT         REFERENCES MAQUINARIA(ID),
    PROVEEDOR       INT         REFERENCES PROVEEDOR(ID), -- FOREIGN KEY TO PROVEEDORES
    FECHA           DATE        DEFAULT CURRENT_DATE,
    DESCRIPCION     VARCHAR,
    EMERGENCIA      BOOLEAN     DEFAULT FALSE,
    REFACCIONES     BOOLEAN     DEFAULT FALSE,
    REEMPLAZO       BOOLEAN     DEFAULT FALSE,
    GARANTIA        BOOLEAN     DEFAULT FALSE,
    COSTO           FLOAT,
    NUMEROORDEN     VARCHAR
);


-- * ZONA DE CAMINADORAS
-- 'N°','DESCRIPCIÓN','MARCA','MODELO','N° SERIE','PERIODO','ACTIVO FIJO'}
-- FIXME EN_USO and EN_SERVICIO might be ignored now
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL148800', 'OT 2013', 'AF/014264', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150480', 'OT 2013', 'AF/014270', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL149874', 'OT 2013', 'AF/014266', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL151435', 'OT 2013', 'AF/014271', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (5, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150479', 'OT 2013', 'AF/014269', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (6, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL148799', 'OT 2013', 'AF/014265', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (7, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150489', 'OT 2013', 'AF/014268', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (8, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL150488', 'OT 2013', 'AF/014267', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (9, 'CAMINADORA  FLEXDECK', 'Life Fitness', 'PV-INTEGRITY-CLST', 'CLL179135', 'OT 2013', 'AF/019988', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (10, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121874', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (11, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121896', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (12, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121897', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (13, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121560', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (14, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121898', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (15, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121558', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (16, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121893', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (17, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121895', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (18, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121894', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (19, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121883', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (20, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121875', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (21, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121876', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (22, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121888', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (23, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121882', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (24, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121886', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (25, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121879', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (26, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121899', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (27, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121878', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (28, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121901', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (29, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121877', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (30, 'CAMINADORA INTEGRITY SERIES TREADMILL', 'Life Fitness', 'PV-INTDX-ALLXXS', 'HHT121881', 'VR 2019', '', 'CAMINADORAS', 'A', 'true', 'true');

-- * ZONA DE ELIPTICAS
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX120509', 'VR 2016', 'AF/014272', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX118997', 'VR 2016', 'AF/014275', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX119240', 'VR 2016', 'AF/014276', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX127477', 'VR 2016', 'AF/014281', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (5, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX121349', 'VR 2016', 'AF/014279', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (6, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX119242', 'VR 2016', 'AF/014278', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (7, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX120335', 'VR 2016', 'AF/014274', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (8, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX118998', 'VR 2016', 'AF/014277', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (9, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX121350', 'VR 2016', 'AF/014280', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (10, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX' , 'CXX120336', 'VR 2016', 'AF/014273', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (11, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110921', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (12, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110595', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (13, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110590', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (14, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110589', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (15, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110594', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (16, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110591', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (17, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110592', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (18, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110596', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (19, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110593', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (20, 'Elípticas Integrity Cross Trainer ', 'Life Fitness', 'PV-INXDX-ALLXXS', 'HXX110920', 'VR 2019', '', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (21, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX', 'CXX143851', 'VR 2016', 'AF/019989', 'ELIPTICAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (22, 'Elíptica Cross Trainer', 'Life Fitness', 'CLSX', 'CXX143845', 'VR 2016', 'AF/019990', 'ELIPTICAS', 'A', 'true', 'true');

-- * ZONA DE BICICLETAS
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25776, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25767, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25856, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25721, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (5, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25785, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (6, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25782, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (7, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25727, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (8, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25762, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (9, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25764, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (10, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25752, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (11, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25757, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (12, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25758, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (13, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25741, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (14, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25761, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (15, 'BICICLETAS', 'Life Fitness', 'PV-ICG-GROUP-IC5', 25737, 'VR 2019', '', 'BICICLETAS', 'A', 'true', 'true');

-- * ZONA DE ESCALADORAS
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (1, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106281', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (2, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106273', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (3, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106291', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA, EN_USO, EN_SERVICIO) VALUES (4, 'Power Mill', 'Life Fitness', 'PV-INPMDX-ALLXXSL', 'PMH106288', 'VR 2019', '', 'ESCALADORAS', 'A', 'true', 'true');

-- * ZONA DE REMADORAS
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ZONA, PLANTA) VALUES (1, 'Lifecycle', 'Life Fitness', 'PV-GROUP-ROW', 'RGX190102038', 'VR 2019', 'REMADORAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ZONA, PLANTA) VALUES (2, 'Lifecycle', 'Life Fitness', 'PV-GROUP-ROW', 'RGX190102031', 'VR 2019', 'REMADORAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ZONA, PLANTA) VALUES (3, 'Lifecycle', 'Life Fitness', 'PV-GROUP-ROW', 'RGX190102037', 'VR 2019', 'REMADORAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ZONA, PLANTA) VALUES (4, 'Lifecycle', 'Life Fitness', 'PV-GROUP-ROW', 'RGX190102036', 'VR 2019', 'REMADORAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ZONA, PLANTA) VALUES (5, 'Lifecycle', 'Life Fitness', 'PV-GROUP-ROW', 'RGX190102032', 'VR 2019', 'REMADORAS', 'A');

-- * ZONA DE PESO AGREGADO
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (1, 'CALF EXTENSION ', 'LIFE FITNESS', 'FZCE2', 314001, 'PR 2014', 'AF/014515', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (2, 'SEATED LEG CURL', 'Hammer Strenght', 'HS-SLC2', '118B028', 'PR 2018', 'AF/022733', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (3, 'LEG CURL', 'Hammer Strenght', 'HS-LC2', '0418B008', 'PR 2018', 'AF/022736', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (4, 'LEG EXTENSION', 'Hammer Strenght', 'HS-LE2', '0118B061', 'PR 2018', 'AF/022731', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (5, 'HIP ADDUCTOR/ ABDUCTOR', 'LIFE FITNESS', 'OST-HAA', '101906701986', 'VR 2019', '', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (6, 'HIP ADDUCTOR/ ABDUCTOR', 'LIFE FITNESS', 'OST-HAA', '101906701987', 'VR 2019', '', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (7, 'GLUTE', 'LIFE FITNESS', 'SS-GL', '0319B043', 'VR 2019', '', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (8, 'HIP AND GLUTE', 'LIFE FITNESS', 'PS-HGSE2', 314002, 'PR 2014', 'AF/014519', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (9, 'ABDOMINAL', 'LIFE FITNESS', 'FZ-AB2', 314001, 'PR 2014', 'AF/014514', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (10, 'TRICEPS EXTENSIÓN', 'Hammer Strenght', 'HS-TE', '319B034', 'VR 2019', '', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (11, 'ARM CURL', 'TECNO GYM', '25C2', 8000567, '', '', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (12, 'PECTORAL FLY ', 'Hammer Strenght', 'HS-PEC2', 1015001, 'PR 2014', 'AF/019635', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (13, 'ROW', 'Hammer Strenght', 'HS-RW', '319B014', 'VR 2019', '', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (14, 'LAT PULL-DOWN', 'Hammer Strenght', 'HS-PD', '118B081', 'PR 2018', 'AF/022735', 'PESO AGREGADO', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (15, 'ASSIST DIP / ASSIST CHIN', 'LIFE FITNESS', 'SS-ADC', '319B026', 'VR 2019', '', 'PESO AGREGADO', 'A');

-- * ZONA DE TABLAS
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (1, 'TABLA PARA ABDOMINALES', 'BH GOLDEN LINE', 'S/M', 'TAB 110719-1', 'OT 2017', 'AF/000070', 'TABLAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (2, 'TABLA PARA ABDOMINALES', 'BH GOLDEN LINE', 'S/M', 'TAB 110719-2', 'OT 2017', 'AF/000072', 'TABLAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (3, 'TABLA PARA ABDOMINALES', 'BH GOLDEN LINE', 'S/M', 'TAB 110719-3', 'OT 2017', 'AF/000071', 'TABLAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (4, 'TABLA PARA ABDOMINALES', 'BH GOLDEN LINE', 'S/M', 'TAB 110719-4', 'OT 2017', 'AF/000074', 'TABLAS', 'A');
INSERT INTO MAQUINARIA(NUMERO, DESCRIPCION, MARCA, MODELO, NSERIE, PERIODO, ACTIVO_FIJO, ZONA, PLANTA) VALUES (5, 'TABLA PARA ABDOMINALES', 'BH GOLDEN LINE', 'S/M', 'TAB 110719-5', 'OT 2017', 'AF/000073', 'TABLAS', 'A');


-- ! PRUEBA PARA PROVEEDORES, REMOVER CUANDO NO SE UTILICE COMO TEST
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('ANDRES', 'UDLAP');
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('CHARLY', 'TSYSTEMS');
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('ERICK', 'EMPRESA');
INSERT INTO PROVEEDOR(NOMBRE, COMPANIA) VALUES ('JACK', 'OVERWATCH');


-- ! PRUEBA PARA MANTENIMIENTOS, REMOVER CUANDO NO SE UTILICE COMO PRUEBA
INSERT INTO MANTENIMIENTO(MAQUINA, PROVEEDOR, FECHA, DESCRIPCION, EMERGENCIA, REFACCIONES, REEMPLAZO, GARANTIA, COSTO, NUMEROORDEN) VALUES (1, 1, CURRENT_DATE, 'CAMBIO DE RUEDAS', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 5200.3, 12);
INSERT INTO MANTENIMIENTO(MAQUINA, PROVEEDOR, FECHA, DESCRIPCION, EMERGENCIA, REFACCIONES, REEMPLAZO, GARANTIA, COSTO, NUMEROORDEN) VALUES (15, 2, CURRENT_DATE, 'DEFECTO', 'TRUE', 'FALSE', 'TRUE', 'TRUE', 734, 14);